version: '3'
services:
  frontend:
    build: ./frontend/
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend:/home/node/app
    ports:
      - "3000:3000"
    command: "npm start"
  backend:
    build: ./backend/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
