version: '3'
services:
  react:
    build: ./react/
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./react:/home/node/app
    ports:
      - "3000:3000"
    command: "npm start"
    networks:
      - demo_app
  django:
    build: ./django/
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django:/code
    ports:
      - "8000:8000"
    networks:
      - demo_app
    depends_on:
      - postgres
  postgres:
    build:
      args:
        - POSTGRES_USER=${DEMO_APPS_POSTGRES_USER}
        - POSTGRES_PASSWORD=${DEMO_APPS_POSTGRES_PASSWORD}
      context: .
      dockerfile: postgres.Dockerfile
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - demo_app
networks:
  demo_app:
